name: Build
on: [push, pull_request, release]

# env:
#   DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  build_txtool:
    name: Build Txtool
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Swift Build
        run: swift build
