name: Build
on: [push, pull_request, release]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  build_txtool:
    name: Build Txtool
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Run Swift Build
        run: swift build
